### ISSUE TITLE
Hi, I wonder know if I want to deploy my own serverless function, what do I do?

### ISSUE THREAD

**Issue by abserari** [bestofjs/bestofjs-backend#8]
Dear, Mr.Michael I'm writing about bestofgo with your appreciation UI, I notice that your UI uses the serverless function and static JSON file deployment. Do you use now command always? If I use vercel, what do I need to change and deploy the GitHub readme detail function?

I provide my sincere work here: https://bestofjs-webui.vercel.app/ .
Appreciate your work again.

**Comment by michaelrambeau** [comment]
Hello @abserari and sorry for the very late reply!

I'm not very interested in providing a "Go version of Best of JS" but the idea is interesting.

Good luck with your projects and thank you for your kind words!
